#!/usr/bin/env python3
"""
Title: run_synthstrip_docker.py
Description: Run FreeSurfer's SynthStrip brain extraction tool via Docker.

Created on: October 16, 2025
Created by: Joshua Auger (joshua.auger@childrens.harvard.edu), Computational Radiology Lab, Boston Children's Hospital
"""

import os
import argparse
import subprocess
import SimpleITK as sitk


def get_input_for_synthstrip(input_path):
    """
    Returns the path to the file that should be passed to SynthStrip.
    - If input is .nii or .nii.gz, return input_path directly.
    - If input is .nhdr or .nrrd, create a temporary .nii file and return its path.
    """
    lower_path = input_path.lower()
    if lower_path.endswith((".nii", ".nii.gz")):
        # No conversion needed
        return input_path, False  # False = not a temp file
    else:
        # Convert to temporary NIfTI
        print(f"Converting {input_path} → temporary NIfTI next to input...")
        img = sitk.ReadImage(input_path)
        nii_path = os.path.splitext(input_path)[0] + "_temp.nii"
        sitk.WriteImage(img, nii_path)
        return nii_path, True  # True = temp file


def make_output_filename(input_path, suffix="_strip", out_ext=".nii"):
    """
    Generate output filename with desired suffix and extension.
    Handles .nii, .nii.gz, .nrrd, .nhdr inputs without producing double extensions.
    """
    lower_path = input_path.lower()

    if lower_path.endswith(".nii.gz"):
        base = input_path[:-7]  # remove '.nii.gz'
        ext = ".nii"  # output extension
    elif lower_path.endswith((".nii", ".nhdr", ".nrrd")):
        base = os.path.splitext(input_path)[0]
        ext = ".nii"  # output extension
    else:
        base = os.path.splitext(input_path)[0]
        ext = ".nii"

    return f"{base}{suffix}{ext}"


def run_synthstrip(input_path, output_path=None, output_mask=False, erode_mask=False):
    """
    Run SynthStrip brain extraction using Docker.
    Optionally output a binary mask and/or apply 1-voxel erosion.
    """
    # Convert to NIfTI if needed
    synthstrip_input, is_temp = get_input_for_synthstrip(input_path)
    input_dir = os.path.dirname(os.path.abspath(synthstrip_input))
    input_filename = os.path.basename(synthstrip_input)

    # Default output filename
    if output_path is None:
        output_path = make_output_filename(input_path)

    docker_cmd = [
        "docker", "run", "--rm",
        "--user", f"{os.getuid()}:{os.getgid()}",
        "-v", f"{input_dir}:/data",
        "freesurfer/synthstrip",
        "-i", f"/data/{input_filename}",
        "-o", f"/data/output_strip.nii",
    ]

    # If mask flag is requested
    if output_mask:
        docker_cmd += ["-m", "/data/output_mask.nii"]

    print(f"Running SynthStrip on {input_filename} ...")
    try:
        result = subprocess.run(docker_cmd, check=True, text=True, capture_output=True)
        print("SynthStrip completed successfully.")
        print(result.stdout)

        # Move stripped output to requested path
        output_tmp = os.path.join(input_dir, "output_strip.nii")
        os.replace(output_tmp, output_path)
        print(f"Stripped output saved to: {output_path}")

        # Handle mask output
        final_mask_path = None
        if output_mask:
            mask_output_path = os.path.join(input_dir, "output_mask.nii")
            final_mask_path = os.path.splitext(output_path)[0] + "_mask.nii"

            if os.path.exists(mask_output_path):
                os.replace(mask_output_path, final_mask_path)
                print(f"Binary mask saved to: {final_mask_path}")
            else:
                print("Warning: Mask file was not generated by SynthStrip.")
                final_mask_path = None

        # --- Apply erosion logic ---
        if erode_mask:
            radius = (1, 1, 1)
            print("Applying 1-voxel erosion...")

            if final_mask_path and os.path.exists(final_mask_path):
                # Erode mask first
                print("Eroding brain mask...")
                mask_img = sitk.ReadImage(final_mask_path)
                eroded_mask = sitk.BinaryErode(mask_img, radius)
                sitk.WriteImage(eroded_mask, final_mask_path)
                print(f"Eroded mask saved to: {final_mask_path}")

                # Then apply eroded mask to the stripped image
                print("Applying eroded mask to stripped image...")
                stripped_img = sitk.ReadImage(output_path)
                eroded_stripped = sitk.Mask(stripped_img, eroded_mask)
                sitk.WriteImage(eroded_stripped, output_path)
                print(f"Eroded stripped image saved to: {output_path}")

            else:
                # No mask: erode the stripped volume directly
                print("Eroding stripped image directly (no mask used)...")
                stripped_img = sitk.ReadImage(output_path)
                binary_mask = sitk.Cast(stripped_img > 0, sitk.sitkUInt8)
                eroded_mask = sitk.BinaryErode(binary_mask, radius)
                eroded_stripped = sitk.Mask(stripped_img, eroded_mask)
                sitk.WriteImage(eroded_stripped, output_path)
                print(f"Eroded stripped image saved to: {output_path}")

        # Optional: convert outputs back to NRRD/NHDR
        if input_path.lower().endswith((".nrrd", ".nhdr")):
            print("Converting stripped output back to NRRD...")
            img_out = sitk.ReadImage(output_path)
            nrrd_out_path = os.path.splitext(output_path)[0] + ".nrrd"
            sitk.WriteImage(img_out, nrrd_out_path)
            print(f"Converted stripped output saved to: {nrrd_out_path}")

            if output_mask and final_mask_path and os.path.exists(final_mask_path):
                print("Converting mask to NRRD...")
                mask_img = sitk.ReadImage(final_mask_path)
                nrrd_mask_path = os.path.splitext(final_mask_path)[0] + ".nrrd"
                sitk.WriteImage(mask_img, nrrd_mask_path)
                print(f"Converted mask saved to: {nrrd_mask_path}")

        # Cleanup temp .nii if created
        if is_temp and os.path.exists(synthstrip_input):
            os.remove(synthstrip_input)

    except subprocess.CalledProcessError as e:
        print("SynthStrip FAILED.")
        print("STDOUT:", e.stdout)
        print("STDERR:", e.stderr)
        raise



def main():
    parser = argparse.ArgumentParser(description="Run SynthStrip brain extraction via Docker.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-i", "--input", help="Path to a single input image file (.nii, .nii.gz, .nrrd, .nhdr)")
    group.add_argument("--inputdir", help="Path to a directory containing multiple NIfTI image files (.nii, .nii.gz)")
    parser.add_argument("-o", "--output", help="Path to save output stripped image (optional)")
    parser.add_argument("--mask", action="store_true", help="If set, also output a binary brain mask")
    parser.add_argument("--erode", action="store_true", help="If set, erode the brain mask by 1 voxel after generation")

    args = parser.parse_args()

    if args.input:
        # Single file
        run_synthstrip(args.input, args.output, output_mask=args.mask, erode_mask=args.erode)
    elif args.inputdir:
        # Directory: iterate over all NIfTI files
        input_dir = os.path.abspath(args.inputdir)
        if not os.path.isdir(input_dir):
            raise ValueError(f"{input_dir} is not a valid directory")

        # Find all .nii and .nii.gz files
        nifti_files = [f for f in os.listdir(input_dir) if f.lower().endswith((".nii", ".nii.gz"))]
        nifti_files.sort()  # optional: sort alphabetically

        if not nifti_files:
            print(f"No NIfTI files found in {input_dir}")
            return

        for f in nifti_files:
            input_path = os.path.join(input_dir, f)
            print(f"\nProcessing {input_path} ...")
            run_synthstrip(input_path, output_mask=args.mask, erode_mask=args.erode)


if __name__ == "__main__":
    main()
